# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTCreator/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 430)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 531, 401))
        self.stackedWidget.setObjectName("stackedWidget")
        self.exchnage = QtWidgets.QWidget()
        self.exchnage.setObjectName("exchnage")
        self.amount_input = QtWidgets.QLineEdit(self.exchnage)
        self.amount_input.setGeometry(QtCore.QRect(270, 60, 113, 21))
        self.amount_input.setObjectName("amount_input")
        self.enter_amount = QtWidgets.QLabel(self.exchnage)
        self.enter_amount.setGeometry(QtCore.QRect(140, 60, 101, 20))
        self.enter_amount.setObjectName("enter_amount")
        self.from_box = QtWidgets.QComboBox(self.exchnage)
        self.from_box.setGeometry(QtCore.QRect(190, 120, 103, 32))
        self.from_box.setObjectName("from_box")
        self.to_box = QtWidgets.QComboBox(self.exchnage)
        self.to_box.setGeometry(QtCore.QRect(370, 120, 103, 32))
        self.to_box.setObjectName("to_box")
        self.convert = QtWidgets.QPushButton(self.exchnage)
        self.convert.setGeometry(QtCore.QRect(150, 220, 100, 32))
        self.convert.setObjectName("convert")
        self.clear = QtWidgets.QPushButton(self.exchnage)
        self.clear.setGeometry(QtCore.QRect(300, 220, 100, 32))
        self.clear.setObjectName("clear")
        self.from_label = QtWidgets.QLabel(self.exchnage)
        self.from_label.setGeometry(QtCore.QRect(140, 130, 58, 16))
        self.from_label.setObjectName("from_label")
        self.to_label = QtWidgets.QLabel(self.exchnage)
        self.to_label.setGeometry(QtCore.QRect(320, 130, 58, 16))
        self.to_label.setObjectName("to_label")
        self.logout_button = QtWidgets.QPushButton(self.exchnage)
        self.logout_button.setGeometry(QtCore.QRect(420, 360, 100, 32))
        self.logout_button.setObjectName("logout_button")
        self.result = QtWidgets.QLabel(self.exchnage)
        self.result.setGeometry(QtCore.QRect(90, 290, 441, 20))
        self.result.setText("")
        self.result.setObjectName("result")
        self.stackedWidget.addWidget(self.exchnage)
        self.auth = QtWidgets.QWidget()
        self.auth.setObjectName("auth")
        self.info = QtWidgets.QLabel(self.auth)
        self.info.setGeometry(QtCore.QRect(220, 50, 81, 31))
        self.info.setObjectName("info")
        self.username = QtWidgets.QLineEdit(self.auth)
        self.username.setGeometry(QtCore.QRect(210, 100, 113, 21))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.auth)
        self.password.setGeometry(QtCore.QRect(210, 150, 113, 21))
        self.password.setObjectName("password")
        self.user_label = QtWidgets.QLabel(self.auth)
        self.user_label.setGeometry(QtCore.QRect(120, 100, 81, 20))
        self.user_label.setObjectName("user_label")
        self.password_label = QtWidgets.QLabel(self.auth)
        self.password_label.setGeometry(QtCore.QRect(120, 150, 81, 20))
        self.password_label.setObjectName("password_label")
        self.login_button = QtWidgets.QPushButton(self.auth)
        self.login_button.setGeometry(QtCore.QRect(210, 240, 100, 32))
        self.login_button.setObjectName("login_button")
        self.stackedWidget.addWidget(self.auth)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enter_amount.setText(_translate("MainWindow", "Enter amount:"))
        self.convert.setText(_translate("MainWindow", "convert"))
        self.clear.setText(_translate("MainWindow", "clear"))
        self.from_label.setText(_translate("MainWindow", "From:"))
        self.to_label.setText(_translate("MainWindow", "To:"))
        self.logout_button.setText(_translate("MainWindow", "Log out"))
        self.info.setText(_translate("MainWindow", "Please log in"))
        self.user_label.setText(_translate("MainWindow", "username:"))
        self.password_label.setText(_translate("MainWindow", "password:"))
        self.login_button.setText(_translate("MainWindow", "Log in"))
